// Action Types

export const FETCH_GITHUB_REPOS = 'FETCH_GITHUB_REPOS';
export const FETCH_GITHUB_COMMITS = 'FETCH_GITHUB_COMMITS';
export const RECEIVE_REPOS = 'RECEIVE_REPOS';
export const RECEIVE_COMMITS = 'RECEIVE_COMMITS';

export const FETCH_PROJECT_INDEX = 'FETCH_PROJECT_INDEX';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const RECEIVE_PROJECT_INDEX = 'RECEIVE_PROJECT_INDEX';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';

// Other

export const MY_GITHUB_LOGIN = 'pgilbertschmitt';
